const article_urls = ["http://en.wikipedia.org/wiki/List_of_unusual_units_of_measurement",
    "http://en.wikipedia.org/wiki/Dancing_Plague_of_1518",
    "http://en.wikipedia.org/wiki/Project_Excelsior",
    "http://en.wikipedia.org/wiki/Voynich_manuscript",
    "http://en.wikipedia.org/wiki/Operation_Paul_Bunyan",
    "http://en.wikipedia.org/wiki/Poe_Toaster",
    "http://en.wikipedia.org/wiki/Dyatlov_Pass_incident",
    "http://en.wikipedia.org/wiki/Time_crystal",
    "http://en.wikipedia.org/wiki/Emu_War",
    "http://en.wikipedia.org/wiki/Largest_organisms",
    "http://en.wikipedia.org/wiki/Tanganyika_laughter_epidemic",
    "http://en.wikipedia.org/wiki/Streisand_effect",
    "http://en.wikipedia.org/wiki/Island_of_stability",
    "http://en.wikipedia.org/wiki/Frequency_illusion",
    "http://en.wikipedia.org/wiki/The_Turk",
    "http://en.wikipedia.org/wiki/Chronovisor",
    "http://en.wikipedia.org/wiki/List_of_cryptids",
    "http://en.wikipedia.org/wiki/Bloop",
    "http://en.wikipedia.org/wiki/Antikythera_mechanism",
    "http://en.wikipedia.org/wiki/Sailing_stones",
    "http://en.wikipedia.org/wiki/Klerksdorp_sphere",
    "http://en.wikipedia.org/wiki/Harvard_Computers",
    "http://en.wikipedia.org/wiki/Collyer_brothers",
    "http://en.wikipedia.org/wiki/Pineapple_Fund",
    "http://en.wikipedia.org/wiki/Erie_Gauge_War",
    "http://en.wikipedia.org/wiki/McCollough_effect",
    "http://en.wikipedia.org/wiki/The_Anarchist_Cookbook",
    "http://en.wikipedia.org/wiki/Will-o%27-the-wisp",
    "http://en.wikipedia.org/wiki/List_of_cognitive_biases",
    "http://en.wikipedia.org/wiki/Tardigrade",
    "http://en.wikipedia.org/wiki/Baghdad_Battery",
    "http://en.wikipedia.org/wiki/List_of_common_misconceptions",
    "http://en.wikipedia.org/wiki/Green_children_of_Woolpit",
    "http://en.wikipedia.org/wiki/Tesla%27s_oscillator",
    "http://en.wikipedia.org/wiki/Aral_Sea",
    "http://en.wikipedia.org/wiki/The_Hum",
    "http://en.wikipedia.org/wiki/London_Beer_Flood",
    "http://en.wikipedia.org/wiki/Paris_syndrome",
    "http://en.wikipedia.org/wiki/Jumping_Frenchmen_of_Maine",
    "http://en.wikipedia.org/wiki/Lynching_of_Frank_Embree"];

const article_names = ["List of Unusual Units of Measurement",
    "Dancing Plague of 1518",
    "Project Excelsior",
    "Voynich Manuscript",
    "Operation Paul Bunyan",
    "Poe Toaster",
    "Dyatlov Pass Incident",
    "Time Crystals",
    "Great Emu War",
    "List of Largest Organisms",
    "Tanganyika Laughter Epidemic",
    "Streisand Effect",
    "Island of Stability",
    "Baader-Meinhof Phenomenon",
    "The Turk",
    "Chronovisor",
    "List of Cryptids",
    "Bloop",
    "Antikythera Mechanism",
    "Sailing Stones",
    "Klerksdorp Spheres",
    "Harvard Computers",
    "Collyer Brothers",
    "Pineapple Fund",
    "Erie Gauge War",
    "McCollough Effect",
    "The Anarchist Cookbook",
    "Will-o'-the-Wisp",
    "List of Cognitive Biases",
    "Tardigrade",
    "Baghdad Battery",
    "List of Common Misconceptions",
    "Green Children of Woolpit",
    "Tesla's Oscillator",
    "Aral Sea",
    "The Hum",
    "London Beer Flood",
    "Paris Syndrome",
    "Jumping Frenchmen of Maine",
    "Lynching of Frank Embree"];


export { article_urls, article_names }; 